spring:
  application:
    name: FindMyVehicle
  profiles:
    active: prod
server:
  post: 8080

logging:
  level:
    root: INFO
    com.findmyvehicle.serviceImpl.home: DEBUG

app:
  dashboard:
    recent-missing-vehicles-limit: 3
